List<Map<String, dynamic>> europeCountry = [
  {"country": "Albania", "flag": "🇦🇱"},
  {"country": "Andorra", "flag": "🇦🇩"},
  {"country": "Austria", "flag": "🇦🇹"},
  {"country": "Belarus", "flag": "🇧🇾"},
  {"country": "Belgium", "flag": "🇧🇪"},
  {"country": "Bosnia and Herzegovina", "flag": "🇧🇦"},
  {"country": "Bulgaria", "flag": "🇧🇬"},
  {"country": "Croatia", "flag": "🇭🇷"},
  {"country": "Cyprus", "flag": "🇨🇾"},
  {"country": "Czech Republic", "flag": "🇨🇿"},
  {"country": "Denmark", "flag": "🇩🇰"},
  {"country": "Estonia", "flag": "🇪🇪"},
  {"country": "Finland", "flag": "🇫🇮"},
  {"country": "France", "flag": "🇫🇷"},
  {"country": "Germany", "flag": "🇩🇪"},
  {"country": "Greece", "flag": "🇬🇷"},
  {"country": "Hungary", "flag": "🇭🇺"},
  {"country": "Iceland", "flag": "🇮🇸"},
  {"country": "Ireland", "flag": "🇮🇪"},
  {"country": "Italy", "flag": "🇮🇹"},
  {"country": "Kosovo", "flag": "🇽🇰"},
  {"country": "Latvia", "flag": "🇱🇻"},
  {"country": "Liechtenstein", "flag": "🇱🇮"},
  {"country": "Lithuania", "flag": "🇱🇹"},
  {"country": "Luxembourg", "flag": "🇱🇺"},
  {"country": "Malta", "flag": "🇲🇹"},
  {"country": "Moldova", "flag": "🇲🇩"},
  {"country": "Monaco", "flag": "🇲🇨"},
  {"country": "Montenegro", "flag": "🇲🇪"},
  {"country": "Netherlands", "flag": "🇳🇱"},
  {"country": "North Macedonia", "flag": "🇲🇰"},
  {"country": "Norway", "flag": "🇳🇴"},
  {"country": "Poland", "flag": "🇵🇱"},
  {"country": "Portugal", "flag": "🇵🇹"},
  {"country": "Romania", "flag": "🇷🇴"},
  {"country": "Russia", "flag": "🇷🇺"},
  {"country": "San Marino", "flag": "🇸🇲"},
  {"country": "Serbia", "flag": "🇷🇸"},
  {"country": "Slovakia", "flag": "🇸🇰"},
  {"country": "Slovenia", "flag": "🇸🇮"},
  {"country": "Spain", "flag": "🇪🇸"},
  {"country": "Sweden", "flag": "🇸🇪"},
  {"country": "Switzerland", "flag": "🇨🇭"},
  {"country": "Turkey", "flag": "🇹🇷"},
  {"country": "Ukraine", "flag": "🇺🇦"},
  {"country": "United Kingdom", "flag": "🇬🇧"},
  {"country": "Vatican City", "flag": "🇻🇦"}
];
